### ISSUE TITLE
Support for Angular 5

### ISSUE THREAD

**Issue by slavede** [Crazyht/ngx-tree-select#68]
I think you can update

    "@angular/core": ">=4.0.0 <5.0.0 || >=4.0.0-beta <5.0.0",
    "@angular/forms": ">=4.0.0 <5.0.0 || >=4.0.0-beta <5.0.0"

and build it to include Angular5.

Do you need to update something in your code to work with Angular 5? 

It really prevents updating Angular to 5.0.

Now, if I try to build my app with Angular 5.0.0. I get:

```
ERROR in ./node_modules/rxjs/_esm5/observable/BoundNodeCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (project\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (project\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (project\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (project\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (project\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (project\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (project\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (project\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (project\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (project\node_modules\typescript\lib\typescript.js:44563:16)
    at checkSourceElement (project\node_modules\typescript\lib\typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (project\node_modules\typescript\lib\typescript.js:41990:21)
    at checkDeferredNodes (project\node_modules\typescript\lib\typescript.js:46828:25)
    at checkSourceFileWorker (project\node_modules\typescript\lib\typescript.js:46863:17)
    at checkSourceFile (project\node_modules\typescript\lib\typescript.js:46842:13)
    at Object.forEach (project\node_modules\typescript\lib\typescript.js:1506:30)
 @ ./node_modules/rxjs/_esm5/observable/bindNodeCallback.js 2:0-76
 @ ./node_modules/rxjs/_esm5/add/observable/bindNodeCallback.js
 @ ./node_modules/rxjs/_esm5/Rx.js
 @ ./node_modules/ngx-tree-select/bundle/ngx-tree-select.es5.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
 @ multi ./src/main.ts
ERROR in ./node_modules/rxjs/_esm5/observable/BoundCallbackObservable.js
Module build failed: TypeError: Cannot read property 'type' of undefined
    at Object.getEffectiveTypeAnnotationNode (project\node_modules\typescript\lib\typescript.js:9341:17)
    at assignContextualParameterTypes (project\node_modules\typescript\lib\typescript.js:41652:25)
    at checkFunctionExpressionOrObjectLiteralMethod (project\node_modules\typescript\lib\typescript.js:41948:29)
    at checkExpressionWorker (project\node_modules\typescript\lib\typescript.js:42959:28)
    at checkExpression (project\node_modules\typescript\lib\typescript.js:42898:42)
    at checkExpressionCached (project\node_modules\typescript\lib\typescript.js:42779:38)
    at checkReturnStatement (project\node_modules\typescript\lib\typescript.js:45418:54)
    at checkSourceElement (project\node_modules\typescript\lib\typescript.js:46763:28)
    at Object.forEach (project\node_modules\typescript\lib\typescript.js:1506:30)
    at checkBlock (project\node_modules\typescript\lib\typescript.js:44563:16)
    at checkSourceElement (project\node_modules\typescript\lib\typescript.js:46742:28)
    at checkFunctionExpressionOrObjectLiteralMethodDeferred (project\node_modules\typescript\lib\typescript.js:41990:21)
    at checkDeferredNodes (project\node_modules\typescript\lib\typescript.js:46828:25)
    at checkSourceFileWorker (project\node_modules\typescript\lib\typescript.js:46863:17)
    at checkSourceFile (project\node_modules\typescript\lib\typescript.js:46842:13)
    at Object.forEach (project\node_modules\typescript\lib\typescript.js:1506:30)
 @ ./node_modules/rxjs/_esm5/observable/bindCallback.js 2:0-68
 @ ./node_modules/rxjs/_esm5/add/observable/bindCallback.js
 @ ./node_modules/rxjs/_esm5/Rx.js
 @ ./node_modules/ngx-tree-select/bundle/ngx-tree-select.es5.js
 @ ./src/app/app.module.ngfactory.js
 @ ./src/main.ts
```

**Comment by slavede** [comment]
Additional info: I've tried to fork your repo and build it locally, but I get a lot of webpack issues which I didn't have time to understand, so I've tried to take source of your project and include it as a module to my project which is angular 5 base, and it works quite fine so I guess you just have to provide build with angular5

**Comment by slavede** [comment]
Yes it did.

Only one thing you'll have to do is in select.service.ts.

Change

`import { Subject } from 'rxjs/Rx';`

to

`import { Subject } from 'rxjs/Subject';`

**Comment by slavede** [comment]
Hey, did you manage to merge it?

**Comment by Crazyht** [comment]
Hi, 

I start to try, but lot of changes on build process/webpack and short time to work on it.

**Comment by Crazyht** [comment]
Hi sorry for long time, my job take large part. I need to made some little changes on ng4 version, you think is right if I fix import for rxjs and remove <5.0.0 in package.json ? 

I watch how can build in ng 5 but lot of change in build process and in this case I think component are not anymore compatible with ng 4.

**Comment by slavede** [comment]
Yeah, you should be able to do that and then use ng-packagr to build it...

**Comment by Thorski** [comment]
I also am getting this error.   Need to change  'rxjs/Rx'  to 'rxjs/Subject'.

**Comment by slavede** [comment]
Yeah, that's just proper way of importing it...you should have do it for ng4 as well, but here, they are more strict.

**Comment by slavede** [comment]
Any success?

**Comment by Crazyht** [comment]
I have made change, I fix 2 other bugs and publish new version.

**Comment by Crazyht** [comment]
Try 0.13.0 (same build just make adaptation for rx and peerDependency)

**Comment by slavede** [comment]
Well, it seems fine to me now. Thanks!
